const vehicles = [
  {
    id: 1,
    name: "Toyota Corolla",
    price: 20000,
    year: 2022,
    model: "LE",
    color: "silver",
    brand: "Toyota",
  },
  {
    id: 2,
    name: "Ford F-150",
    price: 35000,
    year: 2021,
    model: "XLT",
    color: "red",
    brand: "Ford",
  },
  {
    id: 3,
    name: "Honda Civic",
    price: 25000,
    year: 2022,
    model: "EX",
    color: "black",
    brand: "Honda",
  },
  {
    id: 4,
    name: "Chevrolet Camaro",
    price: 40000,
    year: 2021,
    model: "SS",
    color: "blue",
    brand: "Chevrolet",
  },
  {
    id: 5,
    name: "Jeep Wrangler",
    price: 30000,
    year: 2022,
    model: "Sport",
    color: "green",
    brand: "Jeep",
  },
  {
    id: 6,
    name: "Tesla Model 3",
    price: 45000,
    year: 2022,
    model: "Long Range",
    color: "white",
    brand: "Tesla",
  },
  {
    id: 7,
    name: "BMW X5",
    price: 60000,
    year: 2021,
    model: "xDrive40i",
    color: "black",
    brand: "BMW",
  },
  {
    id: 8,
    name: "Mercedes-Benz C-Class",
    price: 50000,
    year: 2022,
    model: "C300",
    color: "silver",
    brand: "Mercedes-Benz",
  },
  {
    id: 9,
    name: "Audi Q7",
    price: 55000,
    year: 2021,
    model: "Premium Plus",
    color: "gray",
    brand: "Audi",
  },
  {
    id: 10,
    name: "Lamborghini Aventador",
    price: 500000,
    year: 2022,
    model: "LP 780-4 Ultimae",
    color: "orange",
    brand: "Lamborghini",
  },
];

[
  {
    id: 1,
    name: "Toyota Corolla",
    price: 20000,
    year: 2022,
    model: "LE",
    color: "silver",
    brand: "Toyota",
  },
  {
    id: 2,
    name: "Ford F-150",
    price: 35000,
    year: 2021,
    model: "XLT",
    color: "red",
    brand: "Ford",
  },
  {
    id: 3,
    name: "Honda Civic",
    price: 25000,
    year: 2022,
    model: "EX",
    color: "black",
    brand: "Honda",
  },
  {
    id: 4,
    name: "Chevrolet Camaro",
    price: 40000,
    year: 2021,
    model: "SS",
    color: "blue",
    brand: "Chevrolet",
  },
  {
    id: 5,
    name: "Jeep Wrangler",
    price: 30000,
    year: 2022,
    model: "Sport",
    color: "green",
    brand: "Jeep",
  },
  {
    id: 6,
    name: "Tesla Model 3",
    price: 45000,
    year: 2022,
    model: "Long Range",
    color: "white",
    brand: "Tesla",
  },
  {
    id: 7,
    name: "BMW X5",
    price: 60000,
    year: 2021,
    model: "xDrive40i",
    color: "black",
    brand: "BMW",
  },
  {
    id: 8,
    name: "Mercedes-Benz C-Class",
    price: 50000,
    year: 2022,
    model: "C300",
    color: "silver",
    brand: "Mercedes-Benz",
  },
  {
    id: 9,
    name: "Audi Q7",
    price: 55000,
    year: 2021,
    model: "Premium Plus",
    color: "gray",
    brand: "Audi",
  },
  {
    id: 10,
    name: "Lamborghini Aventador",
    price: 500000,
    year: 2022,
    model: "LP 780-4 Ultimae",
    color: "orange",
    brand: "Lamborghini",
  },
  {
    id: 11,
    name: "Subaru Outback",
    price: 28000,
    year: 2022,
    model: "Touring XT",
    color: "green",
    brand: "Subaru",
  },
  {
    id: 12,
    name: "Porsche 911",
    price: 120000,
    year: 2021,
    model: "Carrera 4S",
    color: "white",
    brand: "Porsche",
  },
];
